### ISSUE TITLE
Weeding

### ISSUE THREAD

**Issue by DavidBrainard** [BrainardLab/OLApproach_Psychophysics#1]
Please see weeding issues posted for OLApproach_Squint, several of which appear to apply here.

If you need help updating to the ConstrainBackground branch, let me know.

**Comment by JorisVincent** [comment]
Cleaned out old calibration files.

**Comment by JorisVincent** [comment]
Ran successfully after switching over to `ConstrainBackground`-branch; seems like it does no damage to this Approach.
